# app/config/config.yml
liip_imagine:

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public' # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)
                cache_prefix: "media/cache" # media/cache

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"  # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    default_filter_set_settings:
        quality:              75
        jpeg_quality:         ~
        png_compression_level:  ~
        png_compression_filter: ~
        animated:             false
        format:               ~
        cache:                ~
        data_loader:          ~
        default_image:        null
        filters: []
        post_processors: []
    controller:
        filter_action:          liip_imagine.controller:filterAction
        filter_runtime_action:  liip_imagine.controller:filterRuntimeAction
        redirect_response_code: 301
    filter_sets:
        asset:

            # adjust the image quality to 75%
            quality: 50

        # Prototype
        name:
            quality:              100
            jpeg_quality:         ~
            png_compression_level:  ~
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:

                # Prototype
                name:                 []

            post_processors:

                # Prototype
                name:                 []

